"""Fix the refreshToken and User relationship error

Revision ID: 5ae0550c18b4
Revises: cb9056b6b59f
Create Date: 2025-10-10 13:36:42.042545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5ae0550c18b4'
down_revision: Union[str, Sequence[str], None] = 'cb9056b6b59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    # ### end Alembic commands ###
